name: Frontend build and deploy

on:
  push:
    branches: [main]
    paths:
      - packages/frontend/**
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: "build and deploy"
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      HOST_PATH: ${{ secrets.HOST_PATH }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - name: Install root packages
        run: |
          yarn cache clean
          rm -rf node_modules
          yarn install
      - name: Create frontend .env file
        run: |
          cd ./packages/frontend
          rm -f .env

          echo PORT=1360 >> .env
          echo REACT_APP_API_URL=https://api.chat.rem029.com >> .env
          echo REACT_APP_API_URL=CHAT >> .env

          cat .env
      - name: Install frontend packages and install
        run: |
          cd ./packages/frontend
          yarn install
          yarn lint
          yarn build
      - name: Deploy frontend and nginx to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "packages/frontend/build, packages/frontend/nginx, packages/frontend/deploy-frontend.sh"
          target: ${{ secrets.HOST_PATH }}
      - name: Run deploy-frontend.sh on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            PATH=$PATH:/${{secrets.SSH_USER}}/.npm-global/bin
            cd  ${{ secrets.HOST_PATH }}packages/frontend
            npm i -g yarn
            source deploy-frontend.sh
